<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
	<%
String cookieName = "email";
Cookie cookies [] = request.getCookies ();
Cookie myCookie = null;
if (cookies != null)
{
for (int i = 0; i < cookies.length; i++) 
{
if (cookies [i].getName().equals (cookieName))
{
myCookie = cookies[i];
break;
}
}
}
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MOBCART</title>
<meta name="description" content="Its a CLOTHING shopping website, where anyone can buy dress which is categorized by religions and there is a CUSTOM option which is very much usable to make customer's required dress by scaling their body sizes." />
<meta name="keywords" content="speedycart,speedycart.tk,speedy,cart,speedykart,speedkart,clothing,shopping clothing,religion dress,custom clothing," />
<meta name="author" content="Sumit Mistri"/>
<meta name="robots" content="index, follow" />
<!-- META Tags generated by http://www.submitexpress.com/meta-tags-generator.html -->
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



<title>welcome- MOBCART</title>


</head>
<body>

	<div class="controll" style="overflow: hidden;">
		<div class="transparent"></div>
		<div class="middle">MOBCART</div>

		<center>
			<div class="search-box" align="center">
				<form class="form-inline" method="post" action="search2.jsp">
					<input type="text" name="p_name" class="search-txt"
						placeholder="Search product's name...">
					<button type="submit" name="save" class="search-button">
						<i class="fa fa-search"></i>
					</button>
				</form>
			</div>
		</center>
		<div class="button">
			<center>
			<%
				if ((session.getAttribute("email") == null) || (session.getAttribute("email") == "")) {
			%>
			
			<%
				} else {
			%>
			
			<%
				}
			%>
		
		
		
		
						<%
if (myCookie == null) {
%>


<a href="login.jsp" style="text-decoration: none"><input
					type="submit" value="SIGN IN" class="s"></a> &nbsp; 
					
					<a href="registration.jsp" style="text-decoration: none"><input
					type="submit" value="SIGN UP" class="s"></a>&nbsp;
<%
} else {
%> <h3 style="color: #f8f2cb; display: inline;">
<%=myCookie.getValue()%>
</h3>

<%
}
%>
				
					
					<a href="home.jsp" style="text-decoration: none"><input
					type="submit" value="Start Here" class="s"></a>
			</center>
		</div>
		<div class="line">
			<hr width=90% style="border-width: 1px;">
		</div>
		<div class="footer" align="right">

			<a href="https://www.facebook.com/speedycarttk/"><i
				class="fa fa-facebook-f"></i></a> &nbsp;&nbsp;|&nbsp;&nbsp;<a
				href="about.jsp"><b>About us</b></a>&nbsp;&nbsp;|&nbsp;&nbsp;<a
				href="contactform.jsp"><b>Contact us</b> </a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<b>&copy; MOBCART</b>&nbsp;&trade;



		</div>

	</div>






</body>
</html>